package(
    default_visibility = ["//tests:__subpackages__"],
)

test_suite(
    name = "unit",
    tests = ["//tests/unit:test_static_unit"],
)

test_suite(
    name = "integration",
    tests = ["//tests/integration:test_static_integration"],
)
