package(default_visibility = ["//visibility:public"])

exports_files([
    "smileyOne.webp",
    "oldfellow.mp4",
    "KEKW.mp4",
    "ribnikov.based.mp4",
    "smileyOne512x512.png",
    "go_away.mp4",
    "cringe-sniff-dog.jpg",
    "stuffy.jpg",
    "lobster.ttf",
    "journalism.jpg",
])
