package(default_visibility = ["//visibility:public"])

filegroup(
    name = "allstatic",
    srcs = glob([
        "*.mp4",
        "*.jpg",
        "*.webp",
        "*.png",
        "*.ttf",
    ]),
)
